spring:
  config:
    activate:
      on-profile: dev
  application:
    name: S3-Bucket
  servlet:
    multipart:
      enabled: true
      max-request-size: 10000MB
      max-file-size: 6000MB
server:
  port: 8084
  tomcat:
    uri-encoding: UTF-8
jwt: # Store token in a Volute
  secret: ${SECRET}
  tokenDecryptCode: ${TOKEN_DECRYPT_CODE}
api:
  class:
    s3:
      image:
        bucket-name: ${bucket_name}
        access-key: ${access_key}
        secret-key: ${secret_key}
s3:
  api:
    header: /api/image
    end-point:
      upload: /v1/upload
      uploadV2: /v2/upload
      update: /v1/update
      update-URL: ${USER_SERVICE}/user/manage/v1/image/update
cloud-front:
  url: ${CLOUD_FRONT_URL}
service:
  base:
    url:
      user: ${USER_SERVICE}
      search: ${SEARCH_SERVICE}
      feed: ${FEED_SERVICE}
      reel: ${REEL_SERVICE}
      trick: ${TRICK_SERVICE}
      images: ${IMAGES_SERVICE}
  method:
    get:
      user: user/load/v1/get/post/count
rekognition:
  image-count: 5
  video-count: 2
  minimum:
    confidence: 50F
aws:
  bucket:
    region: ${REGION}
  image:
    processing:
      url: ${LAMBDA_FUNCTION_URL}
      uri: /ImageProcessingFuction
      auth-token: ${LAMBDA_AUTH_TOKEN}
video:
  compression:
    timeout: 300    # Timeout in seconds (5 minutes)
    preset: veryfast  # Compression preset (options: ultrafast, superfast, veryfast, faster, fast, medium, slow, slower, veryslow)